### ISSUE TITLE
Username whitelist for sign ups

### ISSUE THREAD

**Issue by hcastilho** [LDSSA/portal#108]
Add a dynamic configuration flag to turn on/off checking a username whitelist for sign-ups.

Probably by overriding `allauth.account.adapter.DefaultAccountAdapter.save_user` on `portal.users.adapters.AccountAdapter` and checking `UserWhitelist`.
Similar to what is done on `portal.users.adapters.SocialAccountWhitelistAdapter`.

**Comment by cimendes** [comment]
Admissions?

**Comment by hcastilho** [comment]
With the admissions portal and the instructor's signup page this is no longer required.
