### ISSUE TITLE
Admissions bugs and improvements

### ISSUE THREAD

**Issue by dominguezmaria** [LDSSA/portal#117]
These issues are order from the most important to the less important.
However, since tomorrow starts the applications phase, and the payments phase is only in two weeks, the ones that are more useful to have now are: 1 (super important), 4 and 7.

**1. I can submit the coding test after time is up**

The state is still `admissions:applications` because the selection period will only start on the 22nd.
The coding test duration is set to 5 minutes.
I started the coding test, and after 5 minutes, the submissions page in the portal shows me this, which is correct:

<img width="1440" alt="Screen Shot 2021-06-20 at 12 03 01" src="https://user-images.githubusercontent.com/16541888/122671669-ba54a400-d1bf-11eb-87e7-28b8b0039618.png">

However,  I can still make submissions, including passing the test, after my test time is over:

<img width="1440" alt="Screen Shot 2021-06-20 at 12 03 27" src="https://user-images.githubusercontent.com/16541888/122671689-cb9db080-d1bf-11eb-9efa-8217884cf97d.png">

<img width="1440" alt="Screen Shot 2021-06-20 at 12 05 45" src="https://user-images.githubusercontent.com/16541888/122671706-e7a15200-d1bf-11eb-9c89-827e502ba9c0.png">

---

**2. Submit student ID**

On the candidate version of the portal, on the payments page (https://portal-staging.lisbondatascience.org/admissions/candidate/payment), when the candidate is a student, we need a box for the candidate to upload the student ID

![Screen Shot 2021-06-19 at 18 30 36](https://user-images.githubusercontent.com/16541888/122670063-ef5cf880-d1b7-11eb-8eb7-42e9ca44d1d1.png)

---

**3. Reset payment**

On the staff version of the portal, on a payment page, there is an option to reset payment.
Sometimes candidates select one ticket type, but then need to change it. Example: a candidate selected student but now can't prove they're a student so they need to change the ticket type to regular. Or someone learned now that their company is willing to pay for their ticket. Or a candidate selected the wrong ticket type. This happens every year.

This reset payment option worked like this:
- the candidate could change their ticket type on the profile
- the staff would click reset payment and a new payment would be generated with the updated value
- on the portal, the student would see the correct amount

Example: https://portal-staging.lisbondatascience.org/admissions/staff/payments/6
<img width="1440" alt="Screen Shot 2021-06-20 at 11 19 57" src="https://user-images.githubusercontent.com/16541888/122670334-73fc4680-d1b9-11eb-85e9-f108d7adf9a3.png">

I tried the reset payment and it gave me 500 error.

It's ok if we can't fix the "Reset" feature as long as we can change the ticket type and update the payment on the back office.

---

**4. Feedback with scores**

Last year the feedback that we provided to the candidates on their submissions had the scores for each question.
Note the scores summary at the top of the page and the score in each question. 

![Screen Shot 2021-06-20 at 11 47 59](https://user-images.githubusercontent.com/16541888/122671191-66e15680-d1bd-11eb-8dbe-83c9cff3733f.png)
![Screen Shot 2021-06-20 at 11 47 52](https://user-images.githubusercontent.com/16541888/122671192-68128380-d1bd-11eb-8666-63e08f106a0f.png)

Now the feedback doesn't include the scores:

<img width="1440" alt="Screen Shot 2021-06-20 at 11 50 45" src="https://user-images.githubusercontent.com/16541888/122671282-c5a6d000-d1bd-11eb-9702-86be25290d69.png">
<img width="1440" alt="Screen Shot 2021-06-20 at 11 50 38" src="https://user-images.githubusercontent.com/16541888/122671284-c7709380-d1bd-11eb-8d00-17c3208dc182.png">

(GitHub doesn't allow me to update an html file, I can send it over for a more complete example!)

---

**5. Emails from admissions@lisbondatascience.org**

All the emails sent from the portal should have `from = admissions@lisbondatascience.org`. This is because in all the communications we're asking candidates to add this email address to their contact lists, in order to avoid SMAP.
Currently the confirm email and reset password emails are being sent from `notification@lisbondatascience.org`.

---

**6. Payments tab missing on nav bar**

On the candidate version of the portal, on the home page. We're in the `admissions:selection` state, and the candidate was selected, meaning he now has to pay the fee.
The nav bar is missing the payments tab.

<img width="1440" alt="Screen Shot 2021-06-20 at 11 30 10" src="https://user-images.githubusercontent.com/16541888/122670657-094c0a80-d1bb-11eb-8c9c-52e26f6f9b0c.png">
<img width="1440" alt="Screen Shot 2021-06-20 at 11 30 05" src="https://user-images.githubusercontent.com/16541888/122670658-0b15ce00-d1bb-11eb-9be5-8e6bf7c863d9.png">

---

**7. Time to finish the coding test**

On the candidate version of the portal, on the home page, in the applications phase, we often say that the candidate has X hours to complete the test. But this is being displayed as: `you only have 3:00:00 to finish it.`

It would be clearer if we said `you only have 3 hours to finish it`.

The admissions test duration will always be in hours, so we could transform this duration into hours and present it always like X hours. Even if it's 3.5 hours, I think it looks better than `you only have 3:30:00 to finish it.`

---

**8. Can't see my submissions when state moves to `admissions:selection`**

On the candidate version of the portal, after the applications are over, the submissions pages are not accessible anymore.
Ideally, we should allow the candidates to see their submissions, but don't allow them to submit anymore.

**Comment by cimendes** [comment]
This needs to be broken into several independent issues
