### ISSUE TITLE
Script to send bulk emails from ElasticEmail

### ISSUE THREAD

**Issue by dominguezmaria** [LDSSA/portal#120]
We have some bulk emails planned regarding admissions.
For Marketing purposes, we send these emails from MailChimp.
But in this case, it would make sense to use the ElasticEmail templates.

Could we have a script that receives as arguments a template ID, a list of email addresses that should receive that email, and other arguments that Elastic may need (like from, etc)?

That would be super useful! 😄

**Comment by cimendes** [comment]
For now we can keep the bulk emails through Comms. Re-open if needed
