### ISSUE TITLE
Admissions portal - Store information as global variables 

### ISSUE THREAD

**Issue by hcastilho** [LDSSA/portal#138]
* ~~Page with timeline and the info in the wiki~~
* Move batch data to variables

**Comment by cimendes** [comment]
TO DO: What needs to be stored in variables? Dates, batch number...

**Comment by cimendes** [comment]
Constance options:
Number of seats
Number of scholarships
Quota
(If quota is to be followed ?)

Django models:
Ticket types and prices
TBD
Limit of company tickets from the same tickets.

Are there other rules like this?

(from #139)

**Comment by Gustavo-SF** [comment]
Closing this since we will review these things and open new issues if needed.
