### ISSUE TITLE
Draft: Move admissions data to database

### ISSUE THREAD

**Issue by hcastilho** [LDSSA/portal#139]
### Constance options
* Number of seats
* Number of scholarships
* Quota
* (If quota is to be followed ?)

### Django models
* Ticket types and prices

**TBD**
Limit of company tickets from the same tickets.
Are there other rules like this?

**Comment by cimendes** [comment]
Is this related to admissions?

**Comment by hcastilho** [comment]
Yes it is.

**Comment by cimendes** [comment]
related to #138
