### ISSUE TITLE
Export instructor's students view as csv

### ISSUE THREAD

**Issue by cimendes** [LDSSA/portal#148]
### Description

Currently, there's no easy way to export the student progress into a workable format such as a CSV. It would be very useful to be able to export the students' information and progress in a file. 

### Functional Spec

The information feeding the [Instructor's students view page](https://github.com/LDSSA/portal/blob/master/portal/academy/views.py#L123) needs to be parsed and provided in simple text format.

### Acceptance criteria

- [ ] A button triggering the export of the table information into a file

**Comment by hcastilho** [comment]
Closed by PR #152
