### ISSUE TITLE
Draft: Admissions not ready for async grading

### ISSUE THREAD

**Issue by hcastilho** [LDSSA/portal#155]

**Comment by cimendes** [comment]
@hcastilho can you please provide some more info on this issue? TY

**Comment by hcastilho** [comment]
Commit 06befe0084808377d7d2b226d98a0443a358e22e changed the grading from sync to async which is required for the academy (some notebooks take a while to run).

But the admissions part of the portal expects the grading to have complete when the page is loaded (after the candidate submits).

We need either to run it sync here and async during the academy or prepare admissions for async.
