### ISSUE TITLE
Bug when exporting students grade from portal to csv file

### ISSUE THREAD

**Issue by PedroRibeiro80** [LDSSA/portal#165]
There is a problem in the portal when exporting the students grades to csv.
The timestamp of "submission date" is split into two fields : %Y-%M-%D and %h:%m:%s . The last field is inserted into csv column "total score". Therefore all students grades are shifted to the right. The names of the columns for grades are therefore wrong.

**Comment by hcastilho** [comment]
Hi!
We tried to reproduce your issue, but were not able to.
The date and time are split with a space and the rest of the csv by a `,`.

How did you open the csv?

**Comment by PedroRibeiro80** [comment]
Hi imported the csv into LibreOffice Calc. I now realized that by default LibreOffice uses space as separator. Specifying "," as delimiter resolves the issue. So please reject it.
