### ISSUE TITLE
[Hacks/Slack]: auto-generation of team channels/group messages

### ISSUE THREAD

**Issue by ramaroesilva** [LDSSA/portal#180]
To speed up team preparation at the start of a hackathon, the slack could create automatically one channel (or group chat) per team and assign the team members (similar to what is done, in the ice breakers in the BootCamp kick-off with the random small groups).

This could be nice, although the balance impact vs effort might not be great.

**Comment by cimendes** [comment]
Given that the academy is temporarily remote, I don't think the effort to implement this will make much sense as it won't be needed for an in-person hackathon. Closing :P (sorry)

**Comment by ramaroesilva** [comment]
Makes sense. One less issue in the list!
