### ISSUE TITLE
Grading BLU09 exercise notebooks consistently fails.

### ISSUE THREAD

**Issue by buedaswag** [LDSSA/portal#189]
The grading of BLU09 exercise notebooks consistently fails due to the notebooks consuming too much memory and crashing the containers that run the grading.
This happens when more than one grading container is running.
On my pc, running the exercise notebook took an extra 4.5gb of ram. The cluster that runs the containers for the portal and grading has 8gb of ram in total.
This means that only one BLU09 grading container can run at a time.

To overcome this problem, several alternatives were mentioned:
1. Limit grading to one container at a time through changing the code for the portal
1. Limit grading to one container at a time through a slack channel where students coordinate with each other to guarantee that only one student is grading at a time
1. Redeploy the cluster on a machine with more ram (this would mean redeploying the portal and i, Miguel anticipate would take several days of full time work to accomplish, therefore in my opinion is not practical)
1. Ask the students to submit the notebooks as soon as possible
1. Extend the deadline for submissions
1. Manually grade and manually set the grade on the portal for each notebook

Next steps
1. Evaluate option 1’s feasibility. If its not feasible then evaluate what other options are available, discuss with other stakeholders, decide and implement
1. Coordinate with teaching so that future BLUs have more manageable ram requirements (what would a good amount of ram be?)

More issues
1. https://github.com/LDSSA/portal/issues/188
1. https://github.com/LDSSA/ldsagrader/issues/7

**Comment by cimendes** [comment]
This is #188
