### ISSUE TITLE
[Capstone] Add option to submit report 1 & 2 on portal 

### ISSUE THREAD

**Issue by cimendes** [LDSSA/portal#197]
This would be a very good *good to have*. Currently, for the capstone, the students submit the app URL through the portal. For batch 5 we are thinking about asking students to submit the reports as PDF. It would be fantastic if we had two submit boxes, one for each report, timestamped when uploading to, what I assume, an s3 bucket. 

Setting priority as high due to this being a time-sensitive decision. Capstone kick off on the 17th of January. Report delivery on the following dates:
- Report 1 delivery on February 6th
- Report 1 resubmission up to March 6th
- Report 2 delivery on March 6th
- Report 2 resubmission up to March 20th

**Comment by hcastilho** [comment]
How will the instructors deal with the feedback?
My understanding was that it was done with notes in the document, what will be used instead?

**Comment by cimendes** [comment]
Hey! The PDFs will be copied to a Drive folder and comments will be added directly to the student. This implies the following flow:

1. Student submits report 1 PDF
2. Instructors add comments to PDF 
3. PDF with comments is sent back to the student (though email? Not quite sure how to do this bit)
4. Student submits a new version of report 1 addressing instructors comments
5. Students submit report 2
6. Instructors add comments to PDF 
7. PDF with comments is sent back to the student (same issue as above)
8. Student submits a new version of report 2 addressing instructors comments

This requires that
- Each report will be submitted twice, one "raw" and one "after correction"
- We can send the reports back to the student with the comments
