### ISSUE TITLE
On Admin, show eligibility in users page view

### ISSUE THREAD

**Issue by cimendes** [LDSSA/portal#204]
<img width="823" alt="image" src="https://user-images.githubusercontent.com/15690332/156764162-c63783a5-a741-4bbd-a1b9-c38272862531.png">

Add a new column "is eligible" with eligibility status for graduation (yes or no)

**Comment by buedaswag** [comment]
here is a page with python logic for determining eligible students

![image](https://user-images.githubusercontent.com/33937027/190480273-32b27283-de5e-48bc-89b6-aaebce015cd6.png)

**Comment by buedaswag** [comment]
done, well done!
![image](https://user-images.githubusercontent.com/33937027/195678511-fd6e9590-3644-4e31-9458-0ad0191d9610.png)
