### ISSUE TITLE
Portal onboarding for new volunteers

### ISSUE THREAD

**Issue by buedaswag** [LDSSA/portal#210]
In order to be productive and be able to contribute to the portal, I recommend doing the following

If you've not doe the django tutorial, or need a refresher, do it here
* https://docs.djangoproject.com/en/4.0/intro/tutorial01/

Spin up the portal locally
* https://ldsa-portal.readthedocs.io/en/latest/running.html#running-locally

**Comment by Gustavo-SF** [comment]
This shouldn't be an issue, but it should be documented.
