### ISSUE TITLE
upgrade python version for setup instructions and SLU 00

### ISSUE THREAD

**Issue by buedaswag** [LDSSA/portal#211]
1. figure out the most appropriate python version going forward
1. should we test the new python version for 
1. test and change the setup instructions for that python version

**Comment by cimendes** [comment]
Issue #222 is related to this. Current instructions pointing toward prep course 2022 readme, which uses python 3.7

**Comment by ypandya4** [comment]
I followed setup instructions from batch 5 and ran all of SLU00 in a python3.8 virtual environment, it works fine.
