### ISSUE TITLE
[Admissions] Reset payment details is not working

### ISSUE THREAD

**Issue by cimendes** [LDSSA/portal#235]
## Overview

<img width="1057" alt="image" src="https://user-images.githubusercontent.com/15690332/186377170-274699eb-7e4a-477c-92f9-0b2f17b9cec4.png">

clicking the button above after changing a ticket type of a student results in a page not found error

<img width="700" alt="image" src="https://user-images.githubusercontent.com/15690332/186377484-67f74b0a-e7b3-4208-9da8-5aafa2d9d7f9.png">

## Expected behaviour

New payment details with the correct amount are generated. There's the caveat that a student can't change from a scholarship to any other type of ticket.

**Comment by Gustavo-SF** [comment]
The reset payment was indeed broken. I only had to adjust the paths to what seemed to be the correct ones.

In the end, the button will execute `postal.staff.views.PaymentResetView` which will update the selection to have +48h of payment due date with the user's new ticket type.
