### ISSUE TITLE
create documentation on what an instructor needs to deliver for a hackathon

### ISSUE THREAD

**Issue by buedaswag** [LDSSA/portal#250]
This must include
* overview of CI/CD process to deploy a hackathon
* how data is split between different files
* folder structure of hackathon files

We should make it easy for someone who did not work with us before to know exactly what they need to deliver in the pull request.

After this issue, we should work on https://github.com/LDSSA/portal/issues/249

**Comment by Gustavo-SF** [comment]
Moved this to #249
