### ISSUE TITLE
Revamp Student List for Instructors

### ISSUE THREAD

**Issue by Gustavo-SF** [LDSSA/portal#319]
## Revamp List

- Add a column with the full name of the student
- Remove Slack ID column
- Remove Submission Date Column (this needs to be evaluated, what is it for?)

![Image](https://github.com/user-attachments/assets/6c45ee72-7096-43a3-a64a-764aec3f3593)

**Comment by brunodaemon2** [comment]
1. Changed column Name data from username to first_name + last_name
2. Removed Slack column from the student list.

![gitstatus](https://github.com/user-attachments/assets/8e2dfddf-4f09-4f76-b443-81c37ea16e57)
![screenChanged](https://github.com/user-attachments/assets/1c7a2d8d-e2d7-4565-bc7a-9c649aab560f)
