### ISSUE TITLE
List of students

### ISSUE THREAD

**Issue by buedaswag** [LDSSA/portal#36]
Instructor's would like to access a list of students with the following info:
* student name, batch they are enrolled in, student email, student github handle

**Comment by hcastilho** [comment]
Were did this request come from?

This is not information for which the portal is a authoritative.

**Comment by buedaswag** [comment]
it came from this request: https://ldsacademy.slack.com/archives/C4MFW8QRF/p1598365789003600

alright :) where should we get this from?

**Comment by buedaswag** [comment]
what would make more sense would be to integrate the admissions portal into the portal, this would give us this list, and help us track the progress of our students
