### ISSUE TITLE
Integrate the admissions portal with the portal

### ISSUE THREAD

**Issue by buedaswag** [LDSSA/portal#37]
following this: https://github.com/LDSSA/portal/issues/36

this integration would remove the need to comunicate information from the admissions portal to the portal in order to track the students's progress

**Comment by hcastilho** [comment]
On batch 4 the admissions process was administred with:
https://github.com/LDSSA/adm-portal
https://github.com/LDSSA/adm-grader-f

**Comment by hcastilho** [comment]
First, we need to collect requirements for the process.

**Comment by Juliana-R** [comment]
Can we make this happen?

This would be a **huge** help for student success and teaching AOR and save us hours of workload and loss of information!

It would help if each student had to mandatorily provide the following info to be admitted:

- one github handle
- full name
- Slack display name
- e-mail

@CatarinaSilva @dominguezmaria

**Comment by minhhoang1023** [comment]
A suggestion: Would it be possible to integrate the admission portal with our deadline Calendar too? So that:
- No need to input deadline again & manual evaluation, which can lead to errors
- Any update on calendar is then synced with the Portal
- Deadline is fixed and same for everyone - (we'll probably cry inside in some cases though..)

**Comment by Juliana-R** [comment]
What is the deadline Calendar you're referring to @minhhoang1023 ?

**Comment by minhhoang1023** [comment]
@Juliana-R It's the Google Calendar (for Students). So let's say we define a deadline for Bootcamp delivery and link it with Google Calendar. In the case that we want to extend the deadline, we can simply change the date on Google Calendar, the portal will be updated and new deadline is applied for everyone.

**Comment by hcastilho** [comment]
Seems like a good nice to have but it would entail quite a bit of work and exploration.
With our current priorities and resources, I don't think it would be a good idea to include this in our initial plans.

But I'm open to being convinced that the benefits are worth the extra work or maybe there's some cool way of receiving updates for calendar events in a friendly way that I'm not seeing.
Maybe a zapier integration with google calendar that can curl the portal with updates in a friendly format or something similar.

**Comment by hcastilho** [comment]
Necessary steps for this integration:
1. Merge admissions portal code on this repo
2. Unify django settings in both projects
3. Unify user model definition
4. Unify URL structure
5. Unify grading subsystem

This is a huge task, I would suggest splitting these steps in new issues referencing back to this one.
