### ISSUE TITLE
Upgrate students to Python 3.X or downgrade testing/running python version to 3.6

### ISSUE THREAD

**Issue by hcastilho** [LDSSA/portal#48]
The Ubuntu version under WSL that we recommend ships with Python 3.6 and students with other setups are using other Python versions.

There are some unpredictable, hard to catch problems with supporting different Python minors, IPython 7.17+ for example requires at least Python 3.7.

We must either validate the notebooks with all Python minors we support or ensure students are using the same Python minor and write documentation on how to update.

Maybe starting with finding out what setup and python version students are running.

**Comment by hershaw** [comment]
Do we use any packages or anything that require a specific version? I'm feeling that if we just select one or the other and stick to it, we wouldn't loose out on anything in particular nor would it be any easier or more difficult.

I guess I mean to ask: are there any super compelling reasons to go with one version or another? If not, we could just pick the one that the most students are already using and make that the official one. Is that what you were thinking @hcastilho ?

**Comment by hcastilho** [comment]
That would be my first choice.
But since most instructors use macs I'm almost positive their version will not match the students (which I believe are mostly under WSL) and instructors are a hard crowd to wrangle :).

We would still need to:
* Write docs to install that version in other systems.
* Change the validator/grader Python version to match.
* Write something to make instructors aware of this.

**Comment by hershaw** [comment]
Well on mac, it's super easy to install another version of python and just start using that so us mac fanboys will just have to bite the bullet and become adults! My feeling though is that it'll be more difficult for the students. Even if there are just 5 or 10 students that need to change their python versions, it might end up being quite a pain in the ass for them... and they're already working pretty hard.

**Comment by hcastilho** [comment]
For the time being, we're going with Python 3.7 for compatibility with the prep-course material.
