### ISSUE TITLE
suggestion -- add option to submit reports + anonymize + code

### ISSUE THREAD

**Issue by Juliana-R** [LDSSA/portal#61]
Add an option to the portal capstone part, where the students can submit their reports.

Ideally the reports should be anonymized so the reviewers can comment them without knowing who's the students, and then traced back to the original GitHub handles ande delivered with comments to the students

The code could also be submitted through the portal.

**Comment by cimendes** [comment]
Closed due to lack of a plan for this. If comments are to be added to the doc directly like batch 4 this won't be possible to do through the portal. Feel free to reopen
