### ISSUE TITLE
change datetime display format to iso

### ISSUE THREAD

**Issue by buedaswag** [LDSSA/portal#65]
Specifically, for displaying the "Submitted at" field of a learning unit, the format should be iso

**Comment by Juliana-R** [comment]
does this mean the timezone will appear on the webpage? If not consider also https://github.com/LDSSA/portal/issues/63

**Comment by hcastilho** [comment]
I would propose merging #65 and #63 a single issue called "Standardize portal date and time formats", which would cover all the portal and backoffice.
Part of this would be identifying what is the preferred display format for datetime, date and time formats.
I find people prefer them in their local time, so I would suggest displaying the time in the user's timezone always including the timezone.
In Python:
```
dt.astimezone(<user timezone>).strftime('%Y-%m-%d %H:%M:%S %Z')
``

@LDSSA/infrastructure

**Comment by hcastilho** [comment]
Deprecated
