### ISSUE TITLE
Change portal from github login to username/password

### ISSUE THREAD

**Issue by hcastilho** [LDSSA/portal#66]
* Registration should be able to be opened/closed and use, or not, an allow list
*Should have email confirmation
* Password reset/recovery
* Should redirect user to profile until all required fields are filled (github handle, slack id)

This issue needs to be done for the new prep course.

**Comment by Juliana-R** [comment]
related with full profile features mentioned in #37

**Comment by hcastilho** [comment]
Creating a link to a DM or profile
https://slack.com/intl/en-pt/help/articles/360003827751-Create-a-link-to-a-members-profile-
