### ISSUE TITLE
Create prep-course repositories and CI flows

### ISSUE THREAD

**Issue by hcastilho** [LDSSA/portal#67]
* Should mostly be copied from batch4-instructors and batch4-students
* Due to time limitations we'll use python 3.7 (and only 3.7) everywhere (both students and instructors)
* Add instructions on installing python 3.7 for every supported platform
* Investigate the possibility of moving the setup instructions to a page on the portal (optional)

**Comment by buedaswag** [comment]
also, as we discussed previously, we should remove vmware from the setup guide, as we will not be supporting it this batch

**Comment by buedaswag** [comment]
will be recreated when planning and developing for 2022 prep course
