### ISSUE TITLE
Create infrastructure for the prep course

### ISSUE THREAD

**Issue by hcastilho** [LDSSA/portal#68]
* AWS RDS database
* DNS hostname
* K8S manifests

**Comment by buedaswag** [comment]
this seems like it can be done by mach 16

**Comment by buedaswag** [comment]
since we wont have a prep course portal in the 2021 batch, does the priority change to be lower and the deadline change to be later?

**Comment by hcastilho** [comment]
Closing, we'll revisit the issue next batch.
