### ISSUE TITLE
Allow instructors to submit learning units

### ISSUE THREAD

**Issue by hcastilho** [LDSSA/portal#7]
For testing purposes it's useful for instructors to be able to submit learning units.
The instructors view should by default not show instructors by have a switch to only show instructors.

**Comment by Juliana-R** [comment]
Hello pre-COVID issue, the time has come: 😅 

Specially, and so we can manage students we would need an **identifier column to filter them from the database without bringing instructors or any other "intruders"**. Implemented in line with issue #37 this would be awesome.

Give me/us whatever task plan to make this and issue #37 get closed. 😅
