### ISSUE TITLE
Create snyk account

### ISSUE THREAD

**Issue by hcastilho** [LDSSA/portal#76]
https://snyk.io/

Then please send me the email to add you to the LDSA snyk org.

**Comment by Juliana-R** [comment]
Does this still stand? I have no idea what this is for. @hcastilho

**Comment by hcastilho** [comment]
Snyk is a service that compiles security issues in libraries and OS images.

The idea is to create security awareness among the people contributing to and maintaining the portal.
While it's not obligatory I would certainly advise it to anyone contributing.

**Comment by hcastilho** [comment]
Timed out
