### ISSUE TITLE
Destroy old portal infrastructure

### ISSUE THREAD

**Issue by buedaswag** [LDSSA/portal#90]
the portal will be merged with the admissions portal and we will need to destroy the old portal infrastructure

this will include:
* make a backup of the database
* remove the pods from the cluster (pods services, ingress)
* check if the existing s3 buckets are identified as being from batch4

**Comment by hcastilho** [comment]
We should also document in the wiki where this information is stored.
I should do the same for previous batches.

**Comment by buedaswag** [comment]
to backup the data from `portal-batch4` RDS instance i used this guide:
* https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_ExportSnapshot.html

which resulted in the data being saved to this bucket
* https://s3.console.aws.amazon.com/s3/buckets/ldsa-portal-batch4-backup?region=eu-west-1
